In [6]:
import numpy as np

In [70]:
reply_matrix = np.array([
    [1,2,5,0,3],
    [2,0,5,0,3],
    [0,0,0,0,0],
    [2,0,0,4,0],
    [0,4,2,0,0] 
])

In [71]:
retweet_matrix = np.array([
    [0,2,4,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,4,3],
    [0,2,5,0,0] 
])

In [72]:
like_matrix = np.array([
    [2,5,1,0,3],
    [0,0,0,0,0],
    [0,5,0,3,3],
    [1,0,0,4,1],
    [0,0,9,0,0] 
])

In [19]:
print(np.argmax(reply_matrix.sum(axis=1)))

0


In [21]:
print(np.argmax(retweet_matrix.sum(axis=1)))

3


In [30]:
print(np.argwhere(((retweet_matrix+reply_matrix)>0).sum(axis=1)>0))

[[0]
 [1]
 [3]
 [4]]


In [46]:
mask = np.ones((5,5))
mask2 = np.eye(5)
mask3 = mask - mask2
q4 = (like_matrix - like_matrix*mask3).sum(axis=1)
print(q4)


[2. 0. 0. 4. 0.]


In [47]:
q3 = (like_matrix-np.diag(np.diag(like_matrix))).sum(axis=1)
print((like_matrix-np.diag(np.diag(like_matrix))).sum(axis=1))

[ 9  0 11  2  9]


In [53]:
q6 = np.argwhere(q4>q3)
q6

array([[3]])

In [55]:
q7 = np.shape(q6[0])
q7

(1,)

In [58]:
q8 = (like_matrix + retweet_matrix + reply_matrix).sum(axis=1)
q8

array([30, 10, 11, 19, 22])

#part 2

In [63]:
non_diag = like_matrix - np.diag(np.diag(like_matrix))
q1 = np.max(non_diag, axis=0)
np.max(non_diag, axis=0)

array([1, 5, 9, 3, 3])

In [65]:
tweets = [2,5,10,4,3]

In [68]:
q2 = np.argwhere(tweets-q1==0)
q2

array([[1],
       [4]])

In [76]:
a = like_matrix + retweet_matrix + reply_matrix
b = a>0
c = b.sum(axis=0)
c

array([3, 3, 3, 2, 4])

In [77]:
d = b.sum(axis=1)
d

array([4, 3, 3, 3, 2])

In [82]:
e = np.argwhere(d == c)
e

array([[1],
       [2]])

In [88]:
like_matrix[1:3,1:3]

array([[0, 0],
       [5, 0]])

Part3

In [90]:
print(reply_matrix)
first = np.where(reply_matrix > like_matrix, reply_matrix*(-0.5), reply_matrix)
print(first)
second = np.where(first == like_matrix, first*(-0.25), first)
print(second)

[[1 2 5 0 3]
 [2 0 5 0 3]
 [0 0 0 0 0]
 [2 0 0 4 0]
 [0 4 2 0 0]]
[[ 1.   2.  -2.5  0.   3. ]
 [-1.   0.  -2.5  0.  -1.5]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.   4.   0. ]
 [ 0.  -2.   2.   0.   0. ]]
[[ 1.    2.   -2.5  -0.   -0.75]
 [-1.   -0.   -2.5  -0.   -1.5 ]
 [-0.    0.   -0.    0.    0.  ]
 [-1.   -0.   -0.   -1.    0.  ]
 [-0.   -2.    2.   -0.   -0.  ]]
